$context = new stdClass;
$context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
$context->api_version = 3;
$context->name = 'layout_4';
$context->description = 'A three-column layout (sidebar, content, sidebar)';
$context->tag = 'Layout Contexts';
$context->conditions = array();
$context->reactions = array();
$context->condition_mode = 0;

// Translatables
// Included for use with string extractors like potx.
t('A three-column layout (sidebar, content, sidebar)');
t('Layout Contexts');
